### ISSUE TITLE
Browser detection

### ISSUE THREAD

**Issue by tomsommer** [IshYoBoy/aaa-ishyoboy-google-chrome-44-ssl-fix#1]
Add browser detection to the plugin so it disables itself (does nothing) for new and old Chrome versions.

It should also not trigger if WordPress is indeed SSL enabled or if the user is not running Chrome.

**Comment by VlooMan** [comment]
Hey, feel free to contribute to the plugin. We wanted to keep it as small, straightforward and as clean as possible. Disabling HTTPS should not be causing any side-effects on other browsers and older versions of Chrome.

**Comment by tomsommer** [comment]
It will long-term if the plugin is never removed.

**Comment by VlooMan** [comment]
Hmm, true.

Are you using Chrome 44 on Windows? What is your user agent? http://whatsmyuseragent.com/
On Mac it contains "Chrome/44.0.2403.89" so I am planning to check for this exact version.

Thanks

**Comment by tomsommer** [comment]
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36

But it's also broken in 45 according to bug reports, and other revisions. I made a pull request to fix the issue in general: #2

**Comment by tomsommer** [comment]
Basically your plugin currently just disables SSL for everything, even on sites that do support SSL or who would want to support it in the future. That's not good, and it will lead to confusion if it's not removed again, so you could end up doing more harm than good down the road.

It currently does more than the name says it does.
